---
title: "Frequently Asked Questions"
author: "Benjamin Guiastrennec"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FAQ}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(xpose)
options(width = 100)

xpdb <- xpdb_ex_pk

knitr::opts_chunk$set(fig.dpi    = 96,
                      fig.align  = 'center', 
                      fig.height = 4, 
                      fig.width  = 4,
                      dev        = 'png',
                      dev.args   = list(type = 'cairo'),
                      out.width  = '75%',
                      comment    = '')
```

## How do I install xpose?
### From CRAN (latest stable release)
1. Install/update xpose with the following command:  
`install.packages('xpose')`

### From github (current development version)
1. Make sure you have the devtools package installed
1. Install/update xpose with the following command:  
`devtools::install_github('UUPharmacometrics/xpose')`

## Are xpose and xpose4 cross compatible packages?
No. While the philosophy behind xpose and xpose4 is similar these are two independent packages.

## Are all xpose4 functionalities present in xpose?
Not yet. The new xpose package has been fully redesigned around ggplot2 and the focus is currently on establishing the bases with basic PK diagnostic plots. New features will be added through future updates.

## How do I suggest an idea for a future version of xpose?
1. Check on [github](https://github.com/UUPharmacometrics/xpose/issues) that this idea has not yet been discussed
1. Read the [CONTRIBUTING.md](https://github.com/UUPharmacometrics/xpose/blob/master/.github/CONTRIBUTING.md) document
1. Open a new issue on [github](https://github.com/UUPharmacometrics/xpose/issues) describing your idea

## How do I report a bug found in xpose?
1. Make sure you are running the latest version of xpose
1. Check on [github](https://github.com/UUPharmacometrics/xpose/issues) that this issue has not yet been reported
1. Read the [CONTRIBUTING.md](https://github.com/UUPharmacometrics/xpose/blob/master/.github/CONTRIBUTING.md) document
1. Open a new issue on [github](https://github.com/UUPharmacometrics/xpose/issues)

