---
title: "Importing model outputs"
author: "Benjamin Guiastrennec"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Importing model outputs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(xpose)

xpdb <- xpdb_ex_pk

knitr::opts_chunk$set(fig.dpi = 96,
                      fig.align = 'center', 
                      fig.height = 4, 
                      fig.width = 4,
                      out.width = '75%')
```


### Import model output
To import the model output files (e.g. NONMEM tables). The function `xpose_data()` collects all model output files and table and organizes them into an R object commonly called `xpdb` for xpose data base. Note that xpose makes use of the [readr](http://readr.tidyverse.org) package to rapidly import big dataset into R.

``` r
xpdb <- xpose_data(runno = '001')
```

### Imported files
#### NONMEM runs
To make full use of the functionality offered by `xpose` the following NONMEM output files should be available:

- `.lst/.out/.res`: used to collect information on the run (`template_titles`) as well as the output table names. Alternatively a model file (`.mod/.ctl`) can be used but some of the information in `template_titles` may not be available.
- `.ext`: used to collect final parameter estimates and residual standard error (RSE)
- `.phi`: used for the random effects and iOFV
- `.cov`: used for the covariance matrix
- `.cor`: used for the correlation matrix
- `.grd`: used for the estimation gradients
- `.shk`: used to compute random effect shrinkage `template_titles`
- output and simulation tables: for the actual data

When importing the files, xpose will return messages to the console and inform of any issue encountered during the import.
```
xpdb <- xpose_data(runno = '001')

Looking for nonmem output tables
Reading: sdtab001, catab001, cotab001, patab001 [$prob no.1]

Looking for nonmem output files
Reading: run001.cor, run001.cov, run001.ext, run001.grd, run001.phi
```

These messages can be silenced with the option `quiet = TRUE`.


#### Others NLME tools
Coming with future releases...


### Structure of the `xpdb` object
A typical `xpdb` object contains 7 levels namely:

- `code`: the parsed model code
- `summary`: contains key information regarding the model. All the information contained in the summary can be used as part of the `template_titles`.
- `data`: contains all output and simulation tables as well as the column indexing
- `files`: contains all output files
- `gg_theme`: an attached ggplot2 theme
- `xp_theme`: an attached xpose theme
- `options`: attached global options

### Glimpse at the `xpdb` object
To quickly get information about an `xpdb` object simply write its name or `print(<xpdb name>)` into the R console press Enter and a summary will be returned.

```
run001.lst overview: 
 - Software: nonmem 7.3.0 
 - Attached files: 
   + tables: $prob no.1: sdtab001, catab001, cotab001, patab001 
   + sim tabs: <none> 
   + output files: run001.cor, run001.cov, run001.ext, run001.grd, run001.phi 
 - gg_theme: theme_readable 
 - xp_theme: theme_xp_default 
 - Options: dir = analysis/models/pk/, quiet = TRUE, manual_import = NULL
```
