context('Check console output function')

print_text <- 'run001.lst overview: \n - Software: nonmem 7.3.0 \n - Attached files: \n   + obs tabs: $prob no.1: catab001.csv, cotab001, patab001, sdtab001 \n   + sim tabs: $prob no.2: simtab001.zip \n   + output files: run001.cor, run001.cov, run001.ext, run001.grd, run001.phi, run001.shk \n   + special: <none> \n - gg_theme: theme_readable \n - xp_theme: theme_xp_default \n - Options: dir = analysis/models/pk/, quiet = FALSE, manual_import = NULL'
prm_text <- '\nThe relative standard errors for omega and sigma are reported on the approximate\nstandard deviation scale (SE/variance estimate)/2.\n\nEstimates for $prob no.1, subprob no.0, method foce\n Parameter  Label      Value       RSE\n THETA1     TVCL       25.58       0.02991\n THETA2     TVV        1.388       0.04342\n THETA3     TVKA       4.735       0.1718\n THETA4     LAG        0.4068      0.01883\n THETA5     RES ERR    0.2455      0.07365\n THETA6     CRCL on CL 0.00857     0.1653\n OMEGA(1,1) IIV CL     0.2034      0.1364\n OMEGA(2,2) IIV V      0.2697      0.1174\n OMEGA(3,3) IIV KA     1.385       0.1159\n SIGMA(1,1)            1       fix  - '
summary_text <- '\nSummary for problem no. 0 [Global information] \n - Software                      @software   : nonmem\n - Software version              @version    : 7.3.0\n - Run directory                 @dir        : analysis/models/pk/\n - Run file                      @file       : run001.lst\n - Run number                    @run        : run001\n - Reference model               @ref        : 000\n - Run description               @descr      : NONMEM PK example for xpose\n - Run start time                @timestart  : Fri Sep 1 01:27:25 CEST 2017\n - Run stop time                 @timestop   : Fri Sep 1 01:27:36 CEST 2017\n\nSummary for problem no. 1 [Parameter estimation] \n - Input data                    @data       : mx19_1.csv\n - Number of individuals         @nind       : 74\n - Number of observations        @nobs       : 1022\n - ADVAN                         @subroutine : 2\n - Estimation method             @method     : foce-i\n - Termination message           @term       : MINIMIZATION SUCCESSFUL\n - Estimation runtime            @runtime    : 00:00:04\n - Objective function value      @ofv        : -1518.108\n - Number of significant digits  @nsig       : 3.6\n - Covariance step runtime       @covtime    : 00:00:04\n - Condition number              @condn      : 6.1\n - Eta shrinkage                 @etashk     : 22 [1], 20.9 [2], 20.5 [3]\n - Epsilon shrinkage             @epsshk     : 7 [1]\n - Run warnings                  @warnings   : (WARNING 2) NM-TRAN INFERS THAT THE DATA ARE POPULATION.\n\nSummary for problem no. 2 [Model simulations] \n - Input data                    @data       : mx19_1.csv\n - Number of individuals         @nind       : 74\n - Number of observations        @nobs       : 1022\n - Estimation method             @method     : sim\n - Number of simulations         @nsim       : 20\n - Simulation seed               @simseed    : 221287\n - Run warnings                  @warnings   : (WARNING 2) NM-TRAN INFERS THAT THE DATA ARE POPULATION.\n                                               (WARNING 22) WITH $MSFI AND \"SUBPROBS\", \"TRUE=FINAL\" ...'
vars_text <- '\nList of available variables for problem no. 1 \n - Subject identifier (id)               : ID\n - Dependent variable (dv)               : DV\n - Independent variable (idv)            : TAD\n - Occasion flag (occ)                   : OCC\n - Dose amount (amt)                     : AMT\n - Event identifier (evid)               : EVID\n - Model typical predictions (pred)      : PRED\n - Model individual predictions (ipred)  : IPRED\n - Model parameter (param)               : KA, CL, V, ALAG1\n - Eta (eta)                             : ETA1, ETA2, ETA3\n - Residuals (res)                       : CWRES, IWRES, RES, WRES\n - Categorical covariates (catcov)       : SEX, MED1, MED2\n - Continuous covariates (contcov)       : CLCR, AGE, WT\n - Compartment amounts (a)               : A1, A2\n - Not attributed (na)                   : DOSE, SS, II, TIME, CPRED'

# Tests start here --------------------------------------------------------
test_that('Check print.xpose_data returns a proper message', {
  expect_equal(capture_output(print(xpdb_ex_pk)), print_text)
})

test_that('Check print.xpose_prm returns a proper message', {
  expect_equal(capture_output(print(get_prm(xpdb_ex_pk, problem = 1))), prm_text)
})

test_that('Check summary.xpose_data returns a proper message', {
  expect_equal(capture_output(summary(xpdb_ex_pk)), summary_text)
})

test_that('Check list_vars returns a proper message', {
  expect_equal(capture_output(list_vars(xpdb_ex_pk, problem = 1)), vars_text)
})
