#' Import NONMEM output into R
#'
#' @description Gather model outputs into a R database
#'
#' @param runno Run number to be evaluated.
#' @param dir Location of the model files.
#' @param file Full file name preferably a `.lst` file. Alternative argument to \code{dir}, \code{prefix},
#' \code{runno} and \code{ext}.
#' @param prefix Prefix of the model file name.
#' @param ext Extension of the model file. Should be one of ".lst" (default), ".out", ".res", ".mod" or ".ctl" for NONMEM.
#' @param gg_theme A ggplot2 theme object (eg. \code{\link[ggplot2]{theme_classic}}).
#' @param xp_theme An xpose theme or vector of modifications to the xpose theme
#' (eg. \code{c(point_color = 'red', line_linetype = 'dashed')}).
#' @param quiet Logical, if \code{FALSE} messages are printed to the console.
#' @param extra_files A vector of additional output file extensions to be imported. Default is ".ext", ".cov", ".cor", ".phi", 
#' ".grd" for NONMEM.
#' @param manual_import Logical, if \code{FALSE} the names of the output tables to import will be collected from the model file 
#' (default). If \code{TRUE} the names of the output tables to import will be generated by combining the table_names argument with 
#' the tab_suffix or sim_suffix arguments as in the Xpose4 package. Tables will be constructed using the following elements in this 
#' order: dir, tab_names, runno, tab/sim_suffix to create file names such as pk/models/sdtab001 or pk/models/sdtab001sim.
#' @param tab_names Only used when \code{manual_import} is set to \code{TRUE}. Provide the name of the tables to import e.g. 'sdtab', 
#' 'patab', 'cotab', 'catab' for NONMEM.
#' @param tab_suffix Only used when \code{manual_import} is set to \code{TRUE}. Default is '', but can be changed to any character 
#' string to be used as suffix in the table names.
#' @param sim_suffix Only used when \code{manual_import} is set to \code{TRUE}. Default is 'sim', but can be changed to any character 
#' string to be used as suffix in the simulation table names.
#' @param ... Additional arguments to be passed to the \code{\link[readr]{read_delim}} functions.
#'
#' @examples
#' \dontrun{
#' xpdb <- xpose_data(file = 'run001.lst')
#' }
#' 
#' @export
xpose_data <- function(runno         = NULL,
                       dir           = NULL,
                       file          = NULL,
                       prefix        = 'run',
                       ext           = '.lst',
                       gg_theme      = theme_readable(),
                       xp_theme      = theme_xp_default(),
                       quiet         = FALSE,
                       extra_files,
                       manual_import = FALSE,
                       tab_names,
                       tab_suffix,
                       sim_suffix,
                       ...) {
  
  if (is.null(runno) && is.null(file)) {
    stop('Argument `runno` or `file` required.', call. = FALSE)
  }
  
  if (is.null(file)) {
    ext  <- make_extension(ext)
    file <- file_path(dir, stringr::str_c(prefix, runno, ext))
  }
  
  if (ext %in% c('.lst', '.out', '.res', '.mod', '.ctl')) {
    software <- 'nonmem'
    model_code <- read_nm_model(file, runno, dir, prefix, ext, quiet)
    if (!manual_import) {
      tbl_names  <- list_nm_tables(model_code)
    } else {
      if (missing(tab_suffix)) tab_suffix <- ''
      if (missing(sim_suffix)) sim_suffix <- 'sim'
      if (missing(tab_names)) {
        tab_names <- c('sdtab', 'mutab', 'patab', 'catab', 'cotab', 
                       'mytab', 'extra', 'xptab', 'cwtab')
      }
      tbl_names  <- file_path(dirname(file), stringr::str_c(tab_names, get_runno(file, prefix))) %>% 
        dplyr::tibble(problem = -1, file = ., firstonly = FALSE, simtab = NA) %>% 
        tidyr::expand(problem = .$problem, file = .$file, firstonly = .$firstonly, simtab = c(FALSE, TRUE)) %>% 
        dplyr::mutate(file = dplyr::if_else(.$simtab, stringr::str_c(.$file, sim_suffix),
                                            stringr::str_c(.$file, tab_suffix))) %>% 
        dplyr::filter(file.exists(.$file))
    }
  } else {
    stop('Model file currently not supported by xpose.', call. = FALSE)
  }  
  
  # Import estimation tables
  msg(c('Looking for ', software, ' table files'), quiet)
  if (software == 'nonmem') {
    data <- tbl_names %>%
      dplyr::filter(.$simtab == FALSE) %>% 
      as.nm.table.list() %>% 
      read_nm_tables(..., quiet = quiet)
  }
  
  # Import simulation tables
  msg(c('\nLooking for ', software, ' simulation files'), quiet)
  if (software == 'nonmem') {
    sim <- tbl_names %>%
      dplyr::filter(.$simtab == TRUE) %>% 
      as.nm.table.list() %>% 
      read_nm_tables(..., quiet = quiet)
  }
  
  # Generate model summary
  if (software == 'nonmem') {
    summary <- summarise_nm_model(file, model_code, software, rounding = xp_theme$rounding)
  }
  
  # Import output files
  msg(c('\nLooking for ', software, ' output files'), quiet)
  if (software == 'nonmem') {
    if (missing(extra_files)) {
      extra_files <- c('.ext', '.cor', '.cov', '.phi', '.grd')
    }
    out_files <- update_extension(file, '') %>% 
      stringr::str_c(make_extension(extra_files)) %>% 
      read_nm_files(quiet = quiet)  
  }
  
  # Label themes
  attr(gg_theme, 'theme') <- as.character(substitute(gg_theme)) 
  attr(xp_theme, 'theme') <- as.character(substitute(xp_theme)) 
  
  # Output xpose_data
  structure(list(code = model_code, summary = summary, files = out_files, 
                 data = data, sim = sim, gg_theme = gg_theme,
                 xp_theme = xp_theme, options = list(dir = dirname(file), quiet = quiet, manual_import = manual_import)), 
            class = c('xpose_data', 'uneval'))
}
